config/routes.rb
Rails.application.routes.draw do
  root 'home#show'
  # get 'home#show'

  resources :known_face_rekognitions

  resources :face_rekognitions

  resources :text_rekognitions

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/text_image.rb
class TextImage < ApplicationRecord
  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/face_rekognitions_controller.rb
class FaceRekognitionsController < ApplicationController
  def show
  end

  def new
  end

  def create
  end

  def update
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/known_face_controller.rb
class KnownFaceController < ApplicationController
  def new

  end
  def destroy

  end
  def create

  end
end

app/controllers/known_face_rekognitions_controller.rb
class KnownFaceRekognitionsController < ApplicationController
  def new
  end

  def create
  end

  def index
  end

  def update
  end

  def destroy
  end
end

app/controllers/text_rekognitions_controller.rb
class TextRekognitionsController < ApplicationController

  def index
    @text_images = TextImage.all
  end

  def show
  end

  def new
  end

  def create
    text_image = TextImage.create(text_image_params)
    text_image_params[:image]
    text_image.save
    redirect_to text_rekognition_path
  end

  def update
  end

  private

  def text_image_params
    params.require(:text_image).permit(:image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/face_rekognition_helper.rb
module FaceRekognitionHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/known_face_helper.rb
module KnownFaceHelper
end

app/helpers/known_face_rekognition_helper.rb
module KnownFaceRekognitionHelper
end

app/helpers/text_rekognition_helper.rb
module TextRekognitionHelper
end

app/views/face_rekognitions/create.html.erb
<h1>FaceRekognition#create</h1>
<p>Find me in app/views/face_rekognition/create.html.erb</p>

app/views/face_rekognitions/new.html.erb
<h1>FaceRekognition#new</h1>
<p>Find me in app/views/face_rekognition/new.html.erb</p>

app/views/face_rekognitions/show.html.erb
<h1>FaceRekognition#show</h1>
<p>Find me in app/views/face_rekognition/show.html.erb</p>

app/views/face_rekognitions/update.html.erb
<h1>FaceRekognition#update</h1>
<p>Find me in app/views/face_rekognition/update.html.erb</p>

app/views/home/show.html.erb
<h1>Please choose your recognition:</h1>

<%= link_to 'face',       face_rekognition_path %>
<br>
<%= link_to 'known face', known_face_rekognition_path %>
<br>
<%= link_to 'text',       text_rekognition_path %>

app/views/known_face_rekognitions/create.html.erb
<h1>KnownFaceRekonition#crete</h1>
<p>Find me in app/views/known_face_rekonition/crete.html.erb</p>

app/views/known_face_rekognitions/delete.html.erb
<h1>KnownFaceRekonition#delete</h1>
<p>Find me in app/views/known_face_rekonition/delete.html.erb</p>

app/views/known_face_rekognitions/index.html.erb
<h1>KnownFaceRekonition#index</h1>
<p>Find me in app/views/known_face_rekonition/index.html.erb</p>

app/views/known_face_rekognitions/new.html.erb
<h1>KnownFaceRekonition#new</h1>
<p>Find me in app/views/known_face_rekonition/new.html.erb</p>

app/views/known_face_rekognitions/update.html.erb
<h1>KnownFaceRekonition#update</h1>
<p>Find me in app/views/known_face_rekonition/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsOnAws</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/text_rekognitions/create.html.erb
<h1>TextRekognition#create</h1>
<p>Find me in app/views/text_rekognition/create.html.erb</p>

app/views/text_rekognitions/index.html.erb
<h1>Rekognizing text images</h1>
<h2>Gallery</h2>
<% @text_images.each do |text_image| %>
  <div class="image-tile">
    <img src="<%= url_for(text_image.image.variant(resize: '100x100')) %>">
  </div>
<% end %>

<h2>Upload images with text</h2>
<div>
  <%= form_for TextImage.new, as: :text_image, url: text_rekognitions_path do |f| %>
    <%=f.file_field :image %>
    <%=f.submit :upload %>
  <% end %>
</div>

app/views/text_rekognitions/new.html.erb
<h1>TextRekognition#new</h1>
<p>Find me in app/views/text_rekognition/new.html.erb</p>

app/views/text_rekognitions/update.html.erb
<h1>TextRekognition#update</h1>
<p>Find me in app/views/text_rekognition/update.html.erb</p>